/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SignUp_SignIn;

import DatabaseConnect.ConnectDB;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Truong Dat
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    Color colorError = new Color(255, 102, 102);

    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
        showHint(tfUsername);
        showHint(tfPassword);
        showHint(tfConfirm);
    }

    public void showHint(JTextField jTextField) {
        Font font = jTextField.getFont();
        font = font.deriveFont(Font.ITALIC);
        jTextField.setFont(font);
        jTextField.setForeground(new Color(51, 51, 51));
    }

    public void hideHint(JTextField jTextField) {
        Font font = jTextField.getFont();
        font = font.deriveFont(Font.PLAIN);
        jTextField.setFont(font);
        jTextField.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPasssword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbConfirm = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        tfConfirm = new javax.swing.JPasswordField();
        lbUsername1 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPasssword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPasssword.setText("Password");
        jPanel1.add(lbPasssword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 78, 33));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("SIGN UP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 100, 60));

        lbConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbConfirm.setText("Confirm password");
        jPanel1.add(lbConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 33));

        tfUsername.setText("Username or ID (7-20 characters, A-z)");
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 230, 30));

        btnSignUp.setBackground(new java.awt.Color(0, 0, 234));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("SIGN UP");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSignUpFocusLost(evt);
            }
        });
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 230, 40));

        tfConfirm.setText("Confirm password");
        tfConfirm.setEchoChar('\u0000');
        tfConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfConfirmFocusLost(evt);
            }
        });
        tfConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(tfConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 230, 30));

        lbUsername1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsername1.setText("Username");
        jPanel1.add(lbUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 78, 33));

        tfPassword.setText("Password (7-20 characters, A-z)");
        tfPassword.setEchoChar('\u0000');
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        jPanel1.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 230, 30));

        btnReset.setBackground(new java.awt.Color(255, 100, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        Connection connection;
        PreparedStatement ps;
        StringBuilder sb = new StringBuilder();
        String password = new String(tfPassword.getPassword());

        String regexUser = "^[[A-Z]|[a-z]][[A-Z]|[a-z]|\\d+|]{7,20}$";
        Pattern pUsername = Pattern.compile(regexUser);
        Matcher mUsername = pUsername.matcher(tfUsername.getText());
        Boolean userCheck = mUsername.matches();

        String regexPass = "^[0-9][a-z][A-Z]{7,20}$";
        Pattern pPassword = Pattern.compile(regexPass);
        Matcher mPass = pUsername.matcher(password);
        Boolean passCheck = mPass.matches();

        if (tfUsername.getText().equals("Username or ID (7-20 characters, A-z)") || tfUsername.getText().equals("")) {
            sb.append("You must enter username\n");
            tfUsername.setBackground(colorError);
            tfUsername.requestFocus();
        } else {
            tfUsername.setBackground(Color.WHITE);
            if (!userCheck) {
                sb.append("Invalid username\n");
                tfUsername.setBackground(colorError);
                tfUsername.requestFocus();
            } else {
                tfUsername.setBackground(Color.WHITE);
            }
        }

        if (password.equals("") || password.equals("Password (7-20 characters, A-z)")) {
            sb.append("You must enter password\n");
            tfPassword.setBackground(colorError);

        } else {
            tfPassword.setBackground(Color.WHITE);
            if (!passCheck) {
                sb.append("Invalid password\n");
                tfPassword.setBackground(colorError);
                tfPassword.requestFocus();
            } else {
                tfConfirm.setBackground(Color.WHITE);
            }
        }

        String confirm = new String(tfConfirm.getPassword());

        if (confirm.equals("") || confirm.equals("Confirm password")) {
            sb.append("You must confirm password\n");
            tfConfirm.setBackground(colorError);

        } else {
            tfConfirm.setBackground(Color.WHITE);
            if (!(password.equals(confirm))) {
                sb.append("Passwords do not match\n");
                tfConfirm.setBackground(colorError);
            } else {
                tfConfirm.setBackground(Color.WHITE);
            }
        }
        if (tfUsername.getText().equals(password)) {
            sb.append("Username and password cannot be the same\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                connection = new ConnectDB().getConnection();
                String query = "Insert into Account values('" + tfUsername.getText() + "','" + password + "')";

                ps = connection.prepareStatement(query);
                ps = connection.prepareStatement(query);
                int record = ps.executeUpdate();
                if (record > 0) {
                    JOptionPane.showMessageDialog(this, "Sign up successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Can not sign up. Username are already exist", "Error", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception e) {
                // TODO: handle exception
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_btnSignUpActionPerformed

    private void tfConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfConfirmActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tfUsername.setText(null);
        tfPassword.setText(null);
        tfConfirm.setText(null);
        tfUsername.setBackground(Color.WHITE);
        tfPassword.setBackground(Color.WHITE);
        tfConfirm.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        btnSignUp.setBackground(new Color(0, 0, 234));
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        btnSignUp.setBackground(new Color(0, 0, 190));
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        btnReset.setBackground(new Color(255, 120, 0));
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        btnReset.setBackground(new Color(255, 90, 0));
    }//GEN-LAST:event_btnResetMouseExited

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        if (tfUsername.getText().equals("Username or ID (7-20 characters, A-z)")) {
            tfUsername.setText(null);
            tfUsername.requestFocus();
            hideHint(tfUsername);
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        if (tfPassword.getText().equals("Password (7-20 characters, A-z)")) {
            tfPassword.setText(null);
            tfPassword.requestFocus();
            tfPassword.setEchoChar('*');
            hideHint(tfPassword);
        }
    }//GEN-LAST:event_tfPasswordFocusGained

    private void btnSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSignUpFocusLost

    }//GEN-LAST:event_btnSignUpFocusLost

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        if (tfUsername.getText().length() == 0) {
            showHint(tfUsername);
            Font font = tfUsername.getFont();
            tfUsername.setText("Username or ID (7-20 characters, A-z)");
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        if (tfPassword.getText().length() == 0) {
            tfPassword.setText(null);
            showHint(tfPassword);
            tfPassword.setText("Password (7-20 characters, A-z)");
            tfPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfConfirmFocusGained
        if (tfConfirm.getText().equals("Confirm password")) {
            tfConfirm.setText(null);
            tfConfirm.requestFocus();
            tfConfirm.setEchoChar('*');
            hideHint(tfConfirm);
        }
    }//GEN-LAST:event_tfConfirmFocusGained

    private void tfConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfConfirmFocusLost
        if (tfConfirm.getText().length() == 0) {
            tfConfirm.setText(null);
            showHint(tfConfirm);
            tfConfirm.setText("Confirm password");
            tfConfirm.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_tfConfirmFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbConfirm;
    private javax.swing.JLabel lbPasssword;
    private javax.swing.JLabel lbUsername1;
    private javax.swing.JPasswordField tfConfirm;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("signup_icon.png")));
    }
}
